#!/bin/bash

argumentManager () {
    case $1 in
        "ascii")
            if [[ -f $2 && $3 == "" ]]
            then
                python3 convert.py $2
            elif [[ -f $2 ]]
            then
                python3 convert.py $2 > $3
            else
                echo "inccorect file"
            fi
            ;;
        *)
            echo "error"
            ;;
    esac
}

argumentManager "$@"