.TH Karla
.SH NAME
Karla (Built by Trishit Dedhia) Version 1.0
.SH SYPNOSIS
karla [options] <skill> -> to manage a skill
karla <skill> [options] -> to execute a skill
.SH DESCRIPTION
Karla is a bash-based package manger designed to run and execute image processing libraries.
.SH LEARN SKILL (Install a library)
karla learn <skill>
.SH EXECUTE SKILL (Use the library)
karla <skill> [options]

An image file is often required to be specified at the end.
.SH UNLEARN SKILL (Uninstall library)
karla unlearn <skill>

Karla can also unlearn all the skills at once when told "all" instead of the skill name.
.SH LIST ALL SKILLS (list all libraries installed)
karla show
.SH UPDATE A SKILL
karla update <skill>
.SH MORE DOCUMENTATION
Please visit trishitdedhia/karla on GitHub to see full documentation.


